envoyproxy/envoy-perf

README.md, benchmark.py
New Number of iterations parameter is added in the high-level script.
=> New high-level parameter added.

support/hooks/prepare-commit-msg
Copying a pattern from the envoy repo, adding a commit hook for DCO signoff.
=> Add support hook for sign-off messages.

siege/front-proxy.yaml
Resolve nits from previous PR form @htuch
=> yaml: cleanup redudnant yaml syntax

siege/siege_result_analysis.py
Signed-off-by: Lizan Zhou <lizan@tetrate.io>
=> fix summary by make throughput greater is better

.circleci/config.yml
Third time is a charm.
Signed-off-by: Harvey Tuch <htuch@google.com>
=> ci: fix CircleCI YAML.

repokitteh.star
Signed-off-by: Itay Donanhirsh <itay@bazoo.org>
=> enable repokitteh

ci/do_ci.sh, nighthawk/include/nighthawk/client/BUILD, nighthawk/include/nighthawk/client/options.h, nighthawk/include/nighthawk/common/BUILD, nighthawk/include/nighthawk/common/rate_limiter.h, nighthawk/source/client/BUILD, nighthawk/source/client/options.proto, nighthawk/source/client/options_impl.cc, nighthawk/source/client/options_impl.h, nighthawk/source/client/utility.cc, nighthawk/source/common/BUILD, nighthawk/source/common/rate_limiter_impl.cc, nighthawk/source/common/rate_limiter_impl.h, nighthawk/source/common/utility.cc, nighthawk/source/common/utility.h, nighthawk/test/BUILD, nighthawk/test/options_test.cc, nighthawk/test/rate_limiter_test.cc, nighthawk/test/utility_test.cc
=> Nighthawk: options, rate_limiter, and utility

.gitmodules, WORKSPACE, ci/run_coverage.sh, nighthawk/BUILD, nighthawk/source/common/BUILD, nighthawk/source/common/statistic_impl.h, tools/gen_compilation_database.py
=> HdrHistogram_c bazelification

cloudperf/distribute_proc.py
=> print() function in distribute_proc.py

cloudperf/store_data.py
=> print() function in store_data.py

cloudperf/benchmark.py
=> print() function in benchmark.py

cloudperf/shell_helpers.py
=> print() function in shell_helpers.py

cloudperf/distribute_proc.py, cloudperf/utils.py
@htuch An oversight in the previous PR.
=> Define xrange() in Python 3

nighthawk/include/nighthawk/client/BUILD, nighthawk/include/nighthawk/client/factories.h, nighthawk/source/client/BUILD, nighthawk/source/client/factories_impl.cc, nighthawk/source/client/factories_impl.h, nighthawk/test/BUILD, nighthawk/test/factories_test.cc, nighthawk/test/mocks.cc, nighthawk/test/mocks.h
=> Nighthawk: Factories + tests

nighthawk/README.md, nighthawk/include/nighthawk/client/BUILD, nighthawk/include/nighthawk/client/benchmark_client.h, nighthawk/include/nighthawk/client/client_worker.h, nighthawk/include/nighthawk/client/factories.h, nighthawk/source/client/BUILD, nighthawk/source/client/benchmark_client_impl.cc, nighthawk/source/client/benchmark_client_impl.h, nighthawk/source/client/client.cc, nighthawk/source/client/client.h, nighthawk/source/client/client_worker_impl.cc, nighthawk/source/client/client_worker_impl.h, nighthawk/source/client/factories_impl.cc, nighthawk/source/client/factories_impl.h, nighthawk/source/common/rate_limiter_impl.cc, nighthawk/source/common/rate_limiter_impl.h, nighthawk/source/common/sequencer_impl.cc, nighthawk/source/common/sequencer_impl.h, nighthawk/source/common/utility.cc, nighthawk/source/common/utility.h, nighthawk/source/common/worker_impl.cc, nighthawk/source/exe/client_main_entry.cc, nighthawk/test/BUILD, nighthawk/test/benchmark_http_client_test.cc, nighthawk/test/client_test.cc, nighthawk/test/client_worker_test.cc, nighthawk/test/factories_test.cc, nighthawk/test/mocks.h, nighthawk/test/sequencer_test.cc
- Adds ClientWorker + tests
- Rate limiter improvement for supporting delayed starts
- WorkerImpl finalizes tls initialization by calling dispatcher.run
=> Nighthawk: Add ClientWorkerXXX

salvo/src/lib/docker/docker_image.py
Define a method in the context manager to run the specified image.  This should make the intent of the context manager a bit more intuitive.
I added a new method to get the private docker client to avoid warnings about using protected members in classes.
=> Use the context manager to run the specified docker image

salvo/src/lib/builder/nighthawk_builder.py, salvo/src/lib/builder/test_nighthawk_builder.py
In this PR, we add the implementation for the NightHawk builder and its tests.
=> Add Implementation for NightHawk builder and its tests

salvo/src/lib/docker/docker_image_builder.py, salvo/src/lib/docker/test_docker_image_builder.py
In this PR we add the implementation for the docker_image_builder module and the associated tests.
=> [Salvo] Add docker_image_builder module and test implementation

salvo/src/lib/benchmark/base_benchmark.py, salvo/src/lib/benchmark/fully_dockerized_benchmark.py, salvo/src/lib/benchmark/scavenging_benchmark.py, salvo/src/lib/benchmark/test_base_benchmark.py, salvo/src/lib/benchmark/test_fully_dockerized_benchmark.py, salvo/src/lib/benchmark/test_scavenging_benchmark.py
In this PR we update the implementation and unit tests for the 'scavenging' benchmark.
There are  a few changes to the base benchmark module needed for the scavenging benchmark implementation and we tweak a few tests to increase code coverage.
=> [Salvo] Add implementation for scavenging benchmark and unit tests

salvo/README.md
This PR  updates the README.md document. Verified that both examples are valid and added a section for the scavenging (to be renamed eventually) benchmark.
Omitting coverage stats since this isn't checked :)
=> [Salvo] Update README.md

salvo/README.md
=> [Salvo] Document of the local execution mode of Salvo (#122)

salvo/README.md
I'm diving into using Salvo's Scavenging Benchmark, and I found some unnecessary fields that need to be removed. 
=> [Salvo] Add further information and remove unnecessary fields about Scavenging Benchmark in README.md

.bazelrc
=> Syncing configuration files from Nighthawk and Envoy (06/02/2022)

salvo/install_deps.sh
add pip deps for salvo_install_deps_install.sh
=> add pip deps for salvo_install_deps_install

ci/run_envoy_docker.sh, salvo/README.md
support salvo build from ci container.
Works on #150.
=> support salvo build from ci container

.bazelrc, ci/run_envoy_docker.sh, salvo/install_deps_ci.sh
=> Syncing configuration files from Nighthawk and Envoy (08/10/2022)

.bazelrc
=> Syncing configuration files from Nighthawk and Envoy (08/31/2022)

.bazelrc
=> Syncing configuration files from Nighthawk and Envoy (09/09/2022)

.bazelrc
=> Syncing configuration files from Nighthawk and Envoy (09/14/2022)

.bazelrc
=> Syncing configuration files from Nighthawk and Envoy (10/06/2022)

.bazelrc
=> Syncing configuration files from Nighthawk and Envoy (10/11/2022)

ci/run_envoy_docker.sh, salvo/install_deps_ci.sh
Fix CI failure due to docker permission issue.
=> Fix CI failure due to docker permission issue

.github/dependabot.yml
=> Enabling dependabot updates for Salvo.

.azure-pipelines/pipelines.yml
=> Always publish the coverage report, even on errors.

salvo/src/lib/common/file_ops.py, salvo/src/lib/job_control_loader.py
=> Use safe_load() when loading Yaml.

.bazelrc
=> Syncing configuration files from Nighthawk and Envoy (01/03/2023)

.bazelrc
Signed-off-by: Xin Huang <xin1.huang@intel.com>
=> Syncing configuration files from Nighthawk and Envoy (01/27/2023)

salvo-remote/azure-pipelines/bazel.yml, salvo-remote/azure-pipelines/salvo_pipelines.yml, salvo-remote/packer-ami-build/salvo-component-vm-x64.pkr.hcl
- the location of the Envoy binary has changed (new `x64` subdirectory).
- the VPC and Security Group IDs changed when I moved Salvo to its own region.
=> Salvo MVP pipeline fixes.

.github/dependabot.yml, .github/workflows/codeql.yml, .github/workflows/scorecard.yml, .github/workflows/stale.yml
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
=> setup ossf scorecard and codql workflows

README.md
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
=> add ossf scorecard badge to README.md
