envoyproxy/envoy-perf

- siege/siege.py
- siege/siege_result_analysis.py
Now that @ambuc added a /contention endpoint, use it in the siege tests to see what contention we experienced under load.
> query envoy for /contention and show results in CSV.

- ci/do_ci.sh
> The LLVM/clang bits shouldn't be CircleCI guarded

- nighthawk/source/common/statistic_impl.cc
- nighthawk/test/statistic_test.cc
Attempting to serialize a `Statistic` with zero values added would
result in a vague complaint: ""JsonObjectWriter was not fully closed".
Some sleuthing pintpointed this to `std::nan` values returned by
`mean()` and `pstdev()`, which would then be passed to
`set_nanos()` in proto duration fields.
> Statistics: fix a bug in `::toProto()` with empty Statistic, add test.

- nighthawk/BUILD
- nighthawk/include/nighthawk/common/platform_util.h
- nighthawk/include/nighthawk/common/rate_limiter.h
- nighthawk/include/nighthawk/common/sequencer.h
- nighthawk/include/nighthawk/common/statistic.h
- nighthawk/source/client/output.proto
- nighthawk/source/common/rate_limiter_impl.h
- nighthawk/source/common/sequencer_impl.cc
- nighthawk/source/common/sequencer_impl.h
- nighthawk/source/common/statistic_impl.cc
- nighthawk/source/common/statistic_impl.h
- nighthawk/test/sequencer_test.cc
- nighthawk/test/statistic_test.cc
- Update Envoy submodule
- Fix hdrhistogram_c build breakage with later Envoy versions
- Add and use a few typedefs
- Update output.proto
- Tidy up some #includes
- Add an 'id' field to Statistic which helps use them in a more generic way + test
- Sequencer takes ownership of the RateLimiter that gets passed in
> Nighthawk: sync up what we have right now with we-amp/nighthawk

- cloudperf/show_graph.py
@htuch A bit-sized subset of #30  Legacy __print__ statements are syntax errors in Python 3 but __print()__ function works as expected in both Python 2 and Python 3.
> print() function in show_graph.py

- cloudperf/database_helpers.py
@htuch A bit-sized subset of #30  Legacy __print__ statements are syntax errors in Python 3 but __print()__ function works as expected in both Python 2 and Python 3.
> print() function in database_helpers.py

- cloudperf/utils.py
> xrange() was removed in Python 3 in favor of range()

- .bazelrc
- .circleci/config.yml
- .gitignore
- bazel/get_workspace_status
- ci/do_ci.sh
- nighthawk/.bazelrc
- nighthawk/bazel/get_workspace_status
- nighthawk/source/client/benchmark_client_impl.cc
- nighthawk/source/client/options_impl.cc
- nighthawk/source/common/statistic_impl.cc
- nighthawk/test/benchmark_http_client_test.cc
- nighthawk/test/utility_test.cc
- This adds ASAN/TSAN to CI testing
- Syncs a few small improvements from the NH branch
- Updates Envoy to the latest
- Envoy stopped incrementing upstream_rq_total for HTTP/1 conn pool
when request is circuit broken. Fix test expectations.
> Nighthawk: ASAN/TSAN, Update Envoy, sync up misc changes 

- ci/run_coverage.sh
- nighthawk/README.md
- nighthawk/include/nighthawk/client/factories.h
- nighthawk/include/nighthawk/client/options.h
- nighthawk/include/nighthawk/client/output_formatter.h
- nighthawk/source/client/client.cc
- nighthawk/source/client/client.h
- nighthawk/source/client/factories_impl.cc
- nighthawk/source/client/factories_impl.h
- nighthawk/source/client/options.proto
- nighthawk/source/client/options_impl.cc
- nighthawk/source/client/options_impl.h
- nighthawk/source/client/output_formatter_impl.cc
- nighthawk/source/client/output_formatter_impl.h
- nighthawk/source/common/statistic_impl.cc
- nighthawk/test/factories_test.cc
- nighthawk/test/mocks.h
- nighthawk/test/options_test.cc
- nighthawk/test/output_formatter_test.cc
- nighthawk/test/test_data/output_formatter.json.gold
- nighthawk/test/test_data/output_formatter.txt.gold
- nighthawk/test/test_data/output_formatter.yaml.gold
- Use the proto as a base to compute CLI output in `ConsoleOutputFormatterImpl` to ensure generic behavior across output formats (it used to do that from the native objects).
- Add --format=[human|json|yaml] option
- Write per-worker statistics in json/yaml output
- Clearer CLI output
- Factorize OutputFormatter creation
- Stop using std::err. 
- Stop writing files, we probably want to do that elsewhere.
> Nighthawk output improvements

- salvo/README.md
- salvo/api/BUILD
- salvo/api/docker_volume.proto
- salvo/api/env.proto
- salvo/api/source.proto
- salvo/salvo.py
- salvo/src/lib/BUILD
- salvo/src/lib/benchmark/BUILD
- salvo/src/lib/benchmark/base_benchmark.py
- salvo/src/lib/benchmark/fully_dockerized_benchmark.py
- salvo/src/lib/benchmark/test_fully_dockerized_benchmark.py
- salvo/src/lib/cmd_exec.py
- salvo/src/lib/constants.py
- salvo/src/lib/docker_image.py
- salvo/src/lib/docker_volume.py
- salvo/src/lib/job_control_loader.py
- salvo/src/lib/test_docker_image.py
- salvo/src/lib/test_job_control_loader.py
This change adds a skeleton for the fully dockerized benchmark flow.
This benchmark method uses docker images for  Envoy, the NightHawk benchmark framework, and the NightHawk binaries.  
Users specify a location where external tests are mapped into the benchmark container and executed.
cc: @mum4k, @oschaaf, @htuch 
Signed-off-by: Alvin Baptiste <alvinsb@gmail.com>
> Fully dockerized flow skeleton

- .gitignore
- ci/do_ci.sh
- salvo/install_deps.sh
- salvo/requirements.txt
- salvo/src/lib/benchmark/BUILD
- salvo/src/lib/benchmark/base_benchmark.py
- salvo/src/lib/benchmark/fully_dockerized_benchmark.py
- salvo/src/lib/benchmark/test_base_benchmark.py
- salvo/src/lib/benchmark/test_fully_dockerized_benchmark.py
- salvo/src/lib/cmd_exec.py
- salvo/src/lib/docker_image.py
- salvo/src/lib/docker_volume.py
- salvo/src/lib/job_control_loader.py
- salvo/src/lib/test_docker_image.py
- salvo/src/lib/test_job_control_loader.py
- salvo/tools/typecheck.sh
In this PR we add the implementation for the skeleton methods, and the accompanying unit tests.
Doc strings were adjusted based on pylint warnings.  The pytype checks were added to the CI script.  This should resolve https://github.com/envoyproxy/envoy-perf/issues/76.
> [Salvo] Add method implementation and populate unit tests

- salvo/src/lib/benchmark/fully_dockerized_benchmark.py
- salvo/src/lib/benchmark/test_fully_dockerized_benchmark.py
- salvo/src/lib/docker/BUILD
- salvo/src/lib/docker/docker_image.py
- salvo/src/lib/docker/test_docker_image.py
In this change we add a context manager to enumerate and stop any lingering docker images from the benchmark.
We also fixed a couple outstanding issues:
1.  in a BUILD file "data" is correctly replaced by "srcs".
2.  fix import statements in the test (for now.  Other files are forthcoming)
> Use a context manager to stop lingering docker images

- salvo/src/lib/BUILD
- salvo/src/lib/benchmark/base_benchmark.py
- salvo/src/lib/benchmark/test_base_benchmark.py
- salvo/src/lib/benchmark/test_fully_dockerized_benchmark.py
- salvo/src/lib/constants.py
- salvo/src/lib/docker/docker_volume.py
- salvo/src/lib/job_control_loader.py
- salvo/src/lib/source_manager.py
- salvo/src/lib/source_tree.py
- salvo/src/lib/test_job_control_loader.py
- salvo/src/lib/test_source_manager.py
- salvo/src/lib/test_source_tree.py
Happy New Year! :)
Changes in this PR include:
- Stub out the source tree and source manager modules and their tests.
- Fix a few instances in a BUILD where `srcs` are labeled as `data`
- Fix the comments in `constants.py` to comply with pylint
cc: @landesherr, @mum4k
> Add source management and test stubs

- salvo/src/lib/BUILD
- salvo/src/lib/common/BUILD
- salvo/src/lib/common/file_ops.py
- salvo/src/lib/common/fileops.py
- salvo/src/lib/common/test_file_ops.py
- salvo/src/lib/source_tree.py
- salvo/src/lib/test_source_tree.py
Add the `source_tree` module that abstracts git operations to manipulate and deduce information about a source tree.
Unit tests for the source tree module are included in this diff.
> Add source_tree implementation and tests

- salvo/src/lib/cmd_exec.py
- salvo/src/lib/common/BUILD
- salvo/src/lib/common/file_ops.py
- salvo/src/lib/common/test_file_ops.py
- salvo/src/lib/source_tree.py
- salvo/src/lib/test_source_tree.py
This change addresses https://github.com/envoyproxy/envoy-perf/issues/90.  When creating temporary directories we use a `TemporaryDirectory` object instead of a string.
> Use TemporaryDirectory vs string for temp directories

- salvo/src/lib/source_manager.py
- salvo/src/lib/test_source_manager.py
- salvo/src/lib/test_source_tree.py
This PR changes a `List` to a `Set` in multiple places the source manager to prevent duplicating tags for benchmarks.
Also fixed an errant whitespace in the `test_source_tree` file.
> De-duplicate image tags when determining what to benchmark

- salvo/src/lib/constants.py
- salvo/src/lib/docker/BUILD
- salvo/src/lib/docker/docker_volume.py
- salvo/src/lib/docker/test_docker_image.py
- salvo/src/lib/docker/test_docker_volume.py
This PR updates the test coverage for the docker module to near 100%
Previously we were skipping these tests due to the lack of the docker socket in CI.  We now mock the operations required to exercise the modules.
```
docker/docker_image.py                         |98.4%   127|    -   0|    -    0
docker/docker_volume.py                        | 100%    51|    -   0|    -    0
```
> Add tests and update to increase docker module coverage

- .gitignore
- ci/do_ci.sh
- salvo/src/lib/docker/docker_image.py
- salvo/src/lib/docker/test_docker_image.py
- salvo/src/lib/test_job_control_loader.py
This PR syncs more test changes for Salvo.  Coverage increases from 95.6% to 97.1%
Since the docker volume. module has its own tests, we remove a redundant one from the job control loader tests.
Also, as part of the test target, we run the coverage script.
> Update test coverage

- salvo/src/lib/builder/BUILD
- salvo/src/lib/builder/base_builder.py
- salvo/src/lib/builder/bazel_setup.py
- salvo/src/lib/builder/envoy_builder.py
- salvo/src/lib/builder/test_base_builder.py
- salvo/src/lib/builder/test_envoy_builder.py
This PR adds the builder module into Salvo.  In the builder module we have classes that encapsulate the steps needed to build Envoy and NightHawk from source.
We have a skeleton implementation here, including the unit tests so that we maintain the test coverage level.
> [Salvo] Add the builder module

- salvo/src/lib/builder/envoy_builder.py
- salvo/src/lib/builder/test_envoy_builder.py
- salvo/src/lib/cmd_exec.py
- salvo/src/lib/constants.py
In this PR we add the implementation for the skeleton upstreamed earlier. 
We add additional changes in existing modules.  Most notably is cmd_exec, we add a second method to execute a command where we are only interested in whether the command exits successfully.
> [Salvo] Add the implementation of the envoy builder

- salvo/src/lib/builder/BUILD
- salvo/src/lib/builder/nighthawk_builder.py
- salvo/src/lib/builder/test_nighthawk_builder.py
- salvo/src/lib/constants.py
In this PR we add a skeleton for the nighthawk builder module.  We also add a couple constants referenced by the builder, and also correct a missing BUILD dependency for the base bulider unit test.
> [Salvo] Add a skeleton of the nighthawk builder module

- salvo/src/lib/docker/BUILD
- salvo/src/lib/docker/docker_image_builder.py
- salvo/src/lib/docker/test_docker_image_builder.py
This PR adds the skeleton for the Salvo docker image builder module and its unit tests.
> [Salvo] Add Docker Image builder and test skeleton

- salvo/src/lib/benchmark/BUILD
- salvo/src/lib/benchmark/test_fully_dockerized_benchmark.py
- salvo/src/lib/builder/test_envoy_builder.py
- salvo/src/lib/builder/test_nighthawk_builder.py
- salvo/src/lib/constants.py
- salvo/src/lib/docker/test_docker_image_builder.py
- salvo/src/lib/docker/test_docker_volume.py
- salvo/src/lib/source_manager.py
- salvo/src/lib/source_tree.py
- salvo/src/lib/test_cmd_exec.py
- salvo/src/lib/test_job_control_loader.py
- salvo/src/lib/test_source_manager.py
- salvo/src/lib/test_source_tree.py
In this PR we address some lingering linter issues and include a few bug fixes
1.  Linter changes include line length fixes, indentation fixes, and import cleanup.
2. We remove the logging import and logger configuration from unit tests
3. Fixed a bug where `shutil.copytree` conflicts with our use of temporary directories.
4. Fixed a bug in the source tree tests where we were comparing a variable to itself.
5. Moving common used strings into `constants` and to module global variables in the source tree tests.
No new features are added in this PR, and coverage is at 97.7%
> [Salvo] Linter and bug fixes

- salvo/install_deps.sh
- salvo/tools/coverage.sh
This small PR fixes a spelling error in the dependency script.  We also update the coverage script to enforce that the overall coverage percentage does not drop below a minimum threshold.  The threshold is set to 97.0%.  Current coverage is at  98%.
> [Salvo] Fix dependency spelling error and enforce coverage percentage

- salvo/src/lib/benchmark/BUILD
- salvo/src/lib/benchmark/binary_benchmark.py
- salvo/src/lib/benchmark/test_binary_benchmark.py
- salvo/src/lib/builder/envoy_builder.py
- salvo/src/lib/builder/test_envoy_builder.py
- salvo/src/lib/run_benchmark.py
- salvo/src/lib/test_run_benchmark.py
This PR adds the 3rd and final benchmark style, the BinaryBenchmark,
which builds Envoy and Nighthawk from source, and tests the native
binaries, rather than docker images.
Signed-off-by: Nolan Varani <landesherr@users.noreply.github.com>
cc: @mum4k @abaptiste
> Add Binary Benchmark Workflow to Salvo

- salvo/README.md
- salvo/src/lib/benchmark/binary_benchmark.py
- salvo/src/lib/builder/envoy_builder.py
- salvo/src/lib/run_benchmark.py
- salvo/src/lib/source_manager.py
- salvo/src/lib/test_run_benchmark.py
- salvo/src/lib/test_source_manager.py
Update the README.md to contain an example of the Job Control
for a binary benchmark.  Also update the binary benchmark to
operate on the specified commit and one prior as is inline with
other implemented benchmarks
cc: @mum4k
> [Salvo] Binary benchmark updates

- salvo/README.md
This small PR fixes a typo in salvo/README.md. Example job control document's field should be singular testVersion instead of testVersions.
Signed-off-by: Sunil Narasimhamurthy <sunnrs@amazon.com>
cc: @mum4k , @abaptiste
> [Salvo] Fix typo in salvo/README.md

- salvo/src/lib/builder/envoy_builder.py
- salvo/src/lib/builder/test_envoy_builder.py
While testing Salvo with Envoy v1.19.0, the docker image failed to build.  Closer examination showed it failed due to the addition of su-exec as a dependency in this [Envoy PR](https://github.com/envoyproxy/envoy/pull/15204).
This change updates the build process to execute the appropriate target and stage the su-exec binary for the docker image generation.
cc @mum4k
> [Salvo] Add su-exec docker image dependency to Salvo build process

- salvo/src/lib/docker_management/docker_image.py
Fix #123 
When failing to run benchmarking test in image, the error message is
not informative to show what happened in image. This commit captures and
shows container error logs after error occurs.
After this change, when failing to run containers, it will exit and show container logs:
```
2022-01-20 09:26:18,687: 2161054 [ ERROR] [docker_image] Failed to run benchmarking test in image: envoyproxy/nighthawk-benchmark-dev:latest, error message: Command '['./benchmarks', '--log-cli-level=info', '-vvvv']' in image 'envoyproxy/nighthawk-benchmark-dev:latest' returned non-zero exit status 5: b'', container logs: b'\x1b[1m============================= test session starts ==============================\x1b[0m\r\nplatform linux -- Python 3.8.10, pytest-6.0.1, py-1.11.0, pluggy-0.13.1 -- …
```
> [Salvo] Capture and show error logs when failing to run container 

- salvo/README.md
- salvo/api/image.proto
- salvo/api/source.proto
- salvo/src/lib/source_manager.py
- salvo/src/lib/test_source_manager.py
Fix #132. Add `test_single_image` and `test_single_commit` option to enable single test mode, which is helpful to the scenario that someone want to test different configuration based on one specific envoy image/commit.
> [Salvo] Add single test mode in Salvo

- .circleci/config.yml
- ci/do_ci.sh
- salvo/src/lib/benchmark/binary_benchmark.py
- salvo/src/lib/benchmark/fully_dockerized_benchmark.py
- salvo/src/lib/builder/base_builder.py
- salvo/src/lib/docker_management/docker_image.py
- salvo/src/lib/docker_management/docker_image_builder.py
- salvo/src/lib/docker_management/test_docker_image.py
- salvo/src/lib/run_benchmark.py
- salvo/src/lib/source_manager.py
- salvo/src/lib/source_tree.py
- salvo/src/lib/test_cmd_exec.py
- salvo/src/lib/test_source_manager.py
- salvo/src/lib/test_source_tree.py
- salvo/tools/coverage.sh
- salvo/tools/format_python_tools.sh
This PR fixes #135:
- Adds `check-format`, `fix_format`(only for local execution) and `coverage` in ci/do_ci.sh and enables them in CircleCI.
- Improves the scripts to make the unit tests minimum threshold configurable, prints out more useful information.
- Fixes one flake8 formatting issues but disables two other flake8 checks, and will re-enable and fix them in another PR.
> Improve CI coverage for Salvo

- salvo/tools/coverage.sh
- salvo/tools/format_python_tools.sh
- salvo/tools/typecheck.sh
The Salvo test and coverage CI workflows show green though there are errors: 
https://app.circleci.com/pipelines/github/gyohuangxin/envoy-perf/13/workflows/e1eb2506-0730-4012-9616-1fbbc9140927/jobs/47?invite=true#step-102-1050
https://app.circleci.com/pipelines/github/gyohuangxin/envoy-perf/13/workflows/e1eb2506-0730-4012-9616-1fbbc9140927/jobs/48?invite=true#step-102-1022
This PR aims to add trapping at above errors and fix them.
> Add error trapping in Salvo test coverage checks

- salvo/README.md
Executing install_deps.sh with sudo may lost proxy environment and cause network fail. Add doc example to avoid that.
> add proxy for salvo dependency install doc

- salvo/README.md
All commands in Salvo's doc are based on envoy-perf/salvo directory, so it will fail to execute `ci/run_envoy_docker.sh 'ci/do_ci.sh build'`. 
I add a annotation reminding to switch to root directory when build Salvo by docker.
> Add annotation to switch to root diretory when building Salvo by docker.

- LICENSE
Marking the repository as licensed under Apache-2.0 which matches the license of Envoy.
> Marking the repository as licensed under Apache-2.0.

- .azure-pipelines/pipelines.yml
- salvo/install_deps.sh
- salvo/tools/coverage.sh
- calculate coverage for all directories, not just `src/lib`, this will be future proof when we add more code directories.
- increase the coverage threshold according to current level.
- split `apt` execution to two commands, installing `docker.io` in a separate execution. This allows installation of the remaining packages to continue on machines that cannot install `docker.io`.
- publish the coverage html report as an artifact in the CI pipeline.
- Rename coverage CI steps from `test` to `coverage`.
- fix a typo and reformat the script.
> Improvements to line coverage analysis.

- salvo/src/lib/builder/test_envoy_builder.py
- salvo/src/lib/run_benchmark.py
- salvo/src/lib/source_tree.py
- salvo/src/lib/test_run_benchmark.py
- salvo/src/lib/test_source_manager.py
- salvo/src/lib/test_source_tree.py
- salvo/tools/coverage.sh
- salvo/tools/format_python_tools.sh
- salvo/tools/requirements.txt
Also:
- reformatted files accordingly. All formatting changes were done by running `./ci/do_ci.sh fix_format`.
- exclude local directory `coveragepy-lcov-support` from flake8 checks.
- adjusting coverage after the formatting changes.
Replaces https://github.com/envoyproxy/envoy-perf/pull/174.
> Bump yapf from 0.30.0 to 0.32.0 in /salvo

- .azure-pipelines/pipelines.yml
- ci/do_ci.sh
Works on #187 
Also include the `System.JobAttempt` in the artifact name to ensure unique artifact names for each retry. This was tested in the Nighthawk repository and will be useful once we re-enable the coverage report.
> Disable coverage report until it is fixed.

- salvo-remote/packer-ami-build/README.md
- salvo-remote/packer-ami-build/salvo-component-vm-x64.pkr.hcl
- salvo-remote/packer-ami-build/salvo-component-vm.sh
These scripts will be executed from the AZP pipeline added in https://github.com/envoyproxy/envoy-perf/pull/197.
Tested on AWS.
> Packer scripts that build AMI for Salvo's component VMs.

- ci/do_ci.sh
- salvo-remote/azure-pipelines/bazel.yml
- salvo-remote/azure-pipelines/salvo_controller.yml
- salvo-remote/azure-pipelines/salvo_pipelines.yml
- salvo-remote/azure-pipelines/scripts/asg_control.sh
- salvo-remote/salvo_remote.go
Done here:
- the pipeline builds `salvo-remote` and the sandbox definitions.
- the pipeline preheats the Salvo ASG (starts at least one agent VM).
- the pipeline executes `salvo-remote`, passing in the build ID.
- allow for build ID overrides - this functionality saves time while debugging and will not be part of the API.
- `salvo-remote` now accepts two flags and prints them out to verify correct plumbing of the build ID.
Example execution: https://dev.azure.com/cncf/envoy/_build/results?buildId=137815&view=results
> The salvo-mvp pipeline now executes the salvo-remote controller.

- salvo-remote/salvo_remote.go
- salvo-remote/salvo_remote_test.go
- salvo-remote/sandboxes/BUILD.bazel
- salvo-remote/sandboxes/instances.go
- salvo-remote/sandboxes/instances_test.go
- salvo-remote/sandboxes/sandboxes.go
- changed type of an instance id from `int` to `int64` since that is what we naturally unmarshal and convert from Terraform.
> Objects and functions that describe sandbox instances.

- salvo-remote/salvo_remote.go
- salvo-remote/salvo_remote_test.go
- salvo-remote/sandboxes/sandboxes.go
- salvo-remote/sandboxes/sandboxes_test.go
- Package sandboxes returns sandbox instances.
- Binary salvo-remote prints out sandbox instances.
> The Salvo controller now receives information about running sandbox instances.

- .bazelrc
- ci/do_ci.sh
- ci/run_envoy_docker.sh
- salvo/requirements.txt
> Syncing configuration files from Nighthawk and Envoy (11/01/2023)

- salvo-remote/README.md
The documents were migrated from Google to MS cloud.
Removed links to ASANA which no longer exist.
> Update links to Salvo documents.

- salvo/README.md
I want to build Salvo following the readme. And I find that virtualenv installation step is missing, which is a necessary dependency for building Salvo.
> Add Python virtualenv installation in Salvo's readme.
